DROP TYPE IF EXISTS category;
DROP TYPE IF EXISTS amount_type;
DROP TABLE IF EXISTS line_item
CASCADE;

CREATE TYPE category AS ENUM
('sales', 'cogs', 'overhead');
CREATE TYPE amount_type AS ENUM
('percent', 'dollars');

CREATE TABLE line_item(
    line_item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    line_item_category category, 
    line_item_name TEXT NOT NULL, 
    amount NUMERIC
(11, 2) NOT NULL, 
    line_item_amount_type amount_type, 
    percent_of INTEGER REFERENCES line_item
(line_item_id) ON
DELETE CASCADE
);
