TRUNCATE TABLE line_item
RESTART IDENTITY CASCADE;

INSERT INTO line_item
    (line_item_category, line_item_name, amount, line_item_amount_type)
VALUES
    ('sales', 'Food', 130000.25, 'dollars'),
    ('sales', 'Beverage', 13000.50, 'dollars'),
    ('sales', 'Catering', 10000.28, 'dollars');


INSERT INTO line_item
    (line_item_category, line_item_name, amount, line_item_amount_type, percent_of)
VALUES
    ('cogs', 'Food', 30, 'percent', 1),
    ('cogs', 'Beverage', 15, 'percent', 2),
    ('cogs', 'Catering', 2000, 'dollars', 3);
-- CREATE TYPE category AS ENUM
-- ('Sales', 'COGS', 'Overhead');
-- CREATE TYPE amount_type AS ENUM
-- ('percent', 'dollars');

-- CREATE TABLE line_item(
--     line_item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
--     line_item_category category, 
--     name TEXT NOT NULL, 
--     amount NUMERIC
-- (11, 2), 
--     line_item_amount_type amount_type, 
--     percent_of INTEGER REFERENCES line_item
-- (line_item_id) ON
-- DELETE CASCADE NOT NULL
-- );
